#!/usr/bin/env bash
# A script to install nginx

sudo apt update
sudo apt install nginx -y
#sudo ufw enable -y
sudo ufw allow 'Nginx HTTP'
sudo ufw allow ssh
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
