#!/usr/bin/env bash
# A script that redirects a webpage

if [ $# -lt 3 ]; then
        echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
        exit 1
fi
sudo vim /etc/nginx/sites-enabled/default
rewrite ^/redirect_me https://blog.enigma.com permanent;
sudo systemctl restart nginx
