#!/usr/bin/env bash
# A script that redirects a webpage

sudo apt update
sudo apt install nginx -y
#sudo ufw enable -y
sudo ufw allow 'Nginx HTTP'
sudo ufw allow ssh
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart

# Redirect /redirect_me to https://www.youtube.com/watch?v=QH2-TGUlwu4
#sudo vim /etc/nginx/sites-enabled/default
#rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
#sudo service nginx restart

sed -i 's/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;/' /etc/nginx/sites-enabled/default

# A custom page that contains Ceci n'est pas une page.
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# configure the page to return 404-error 
sed -i 's/server_name _;/server_name _;\n\terror_page 404 \/404.html;' /etc/nginx/sites-enabled/default

sudo service nginx restart

