#!/usr/bin/env bash
# A script to generate a server

#setting up the ssh agent
eval $("ssh-agent")

# The path to the identity_file
ssh-add ~/.ssh/school

#server of the user
ssh ubuntu@54.197.102.78
