#!/usr/bin/env bash
# a script that displays Best School 10times, but for the 9th iteration, display Best school and then hi

i="1"
while [ $i -le 10 ]; do
	if [ "$i" -eq "9" ]; then
		echo "Best school"
		echo "hi"
	else
		echo "Best School"
	fi
	i=$((i+1))
done
